### ISSUE TITLE
Projects are not saving to lessons properly

### ISSUE THREAD

**Issue by WenInCode** [Daimonos/meanScaffold#1]
I think this might be happening on the node side, but I haven't actually checked yet. 

### Scenario

- create new lesson
- project shows it is part of the lesson object
- submit lesson and get redirected to lessons search page
- project doesn't appear to be there 

### Possible reasons

- Angular end not adding project to lesson properly (dont think this is it)
- Node end not saving the project properly to the lesson
- I might just not be accessing it correctly in the search jade file.

I will look into this sometime tomorrow if it's not already fixed.

**Comment by WenInCode** [comment]
Right, so the model as it is is storing the Project as an array within the lessons. So for now I am accessing it by `lesson.project[0].jobName` . Can you use schemas within schemas (like the projects) without storing them as arrays?

**Comment by Daimonos** [comment]
Mongoose only lets you embed schemas as arrays. Not quite sure why. Sorry I think I addressed the issue before reading this
I'm not sure how we can get around it
